name: Prymal Shopify 90-day Forecast
run-name: ${{ github.actor }} - Shopify 90-day Forecast
on: 
  push:
    paths:
      - '**/scripts/shopify_demand_forecast_90_days.py*'
  schedule:
    - cron: '0 7 1 * *'  # Runs at 7 AM on the 1st of every month
jobs:
  shopify_90_day_forecast:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3
      - run: echo "${{ github.repository }} repository has been cloned to the runner"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Set up Python env
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      - name: Forecast Shopify Sales
        env: 
          AWS_ACCESS_KEY:  ${{ secrets.AWS_ACCESS_KEY }}
          AWS_ACCESS_SECRET: ${{ secrets.AWS_ACCESS_SECRET }}
          S3_PRYMAL_ANALYTICS: ${{ secrets.S3_PRYMAL_ANALYTICS }}
        run: python scripts/demand_forecasting.py 

      - run: echo "Job status - ${{ job.status }}."
