name: Prymal Shopify Demand Forecast (90,120,150 days)
run-name: ${{ github.actor }} - Shopify Demand Forecast (90,120,150 days)
on: 
  workflow_dispatch:
  # push:
  #   paths:
  #     - '**/scripts/shopify_demand_forecast_90_days.py'
      # -  '**/workflows/shopify_demand_forecast_90_days.yml'
  schedule:
    - cron: '0 10 * * *'  # Runs at 10 AM every day 
jobs:
  shopify_demand_forecast:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3
      - run: echo "${{ github.repository }} repository has been cloned to the runner"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Set up Python env
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      - name: Forecast Shopify Sales
        env: 
          AWS_ACCESS_KEY:  ${{ secrets.AWS_ACCESS_KEY }}
          AWS_ACCESS_SECRET: ${{ secrets.AWS_ACCESS_SECRET }}
          S3_PRYMAL_ANALYTICS: ${{ secrets.S3_PRYMAL_ANALYTICS }}
        run: python scripts/shopify_demand_forecast_90_days.py 

      - run: echo "Job status - ${{ job.status }}."
